# fly.toml app configuration file generated for ctl-api-v2-backend on 2023-11-22T16:14:07-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ctl-api-v2-backend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
